version: '3'
services:
  tars:
    image: 'tarscloud/framework:stable'
    container_name: "framework"
    environment:
      - MYSQL_HOST=127.0.0.1
      - MYSQL_ROOT_PASSWORD=root@123456
      - MYSQL_USER=root
      - MYSQL_PORT=3306
      - REBUILD=false
      - INET=eth0
      - SLAVE=false
    volumes:
      - './data/tars:/data/tars'
      - '/Users/tlingyx/tools/linux/etc/localtime:/Users/tlingyx/tools/linux/etc/localtime'
    network_mode: 'host'